version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    FRONTEND: "app/frontend"
    BACKEND: "app/backend"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash linux-install-1.10.1.466.sh
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Building frontend ClojureScript app
      - cd $FRONTEND && bash build.sh
      - cd ../..
      - cd $BACKEND
      - bash resources.sh
      - bash build.sh
cache:
  paths:
    - '/root/.m2/**/*'
