version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    FRONTEND: "app/frontend"
    BACKEND: "app/backend"
    IMAGE_REPO_NAME: "teet-service"
    IMAGE_TAG: "latest"
    ECS_TASK_NAME: "teet-service"
    AWS_DEFAULT_REGION: "eu-central-1"

  parameter-store:
    AWS_ACCOUNT_ID: "/teet-dev/aws-account-id"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash linux-install-1.10.1.466.sh
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Building frontend ClojureScript app
      - cd $FRONTEND
      - bash build.sh
      - bash resources.sh
      - cd ../..
      - cd $BACKEND
      - bash build.sh
  post_build:
   commands:
     - cd ../..
     - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_TASK_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > service.imagedefinitions.json
artifacts:
   files:
     - frontend-*.zip
     - service.imagedefinitions.json
cache:
  paths:
    - '/root/.m2/**/*'
