version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    FRONTEND: "app/frontend"
    CHROMIUM_BROWSER: "/usr/bin/chromium-browser"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Download Chromium browser
      - apt-get update
      - apt-get install -y chromium-browser
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash linux-install-1.10.1.466.sh
  pre_build:
    commands:
      - hash -r
      - echo `which chromium-browser`
      - cd $FRONTEND
      - timeout 5m clojure -A:test
  build:
    commands:
      - echo Building frontend ClojureScript app
      - cd $FRONTEND
      - bash build.sh
      - bash resources.sh
artifacts:
   files:
     - frontend-*.zip
cache:
  paths:
    - '/root/.m2/**/*'
