Description:
  The periodic datasource-import job - builds and runs app/datasource-import 
  to get data from MNT GIS data servers and insert into the
  PostgreSQL/PostGIS DB through the REST API provided by PostgREST.

Parameters:
  SharedResourceStack:
    Description: Name of an active CloudFormation stack that contains shared resources, such as the VPC.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: "teet-ci"
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"


Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      Description: Run datasource-import job
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
      Name: !Ref 'AWS::StackName'
      ServiceRole: arn:aws:iam::512288025010:role/service-role/codebuild-teet-deploy-service-role
      Source:
        Type: GITHUB
        BuildSpec: ci/datasource-import/buildspec.yml
        Location: https://github.com/solita/mnt-teet

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "cron(58 8 15 * ? *)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "CodeBuildProject"
              - "Arn"
          Id: "CodeBuildTarget"
          RoleArn: !GetAtt RunCodeBuildJobRole.Arn

  RunCodeBuildJobRole:
    Type: "AWS::IAM::Role"
    DependsOn: CodeBuildProject
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StartTask 
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codebuild:StartBuild'
                Resource:
                  - !GetAtt CodeBuildProject.Arn

