version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash linux-install-1.10.1.466.sh
      - echo Download babashka
      - curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-babashka
      - chmod +x install-babashka
      - ./install-babashka
  build:
    commands:
      - sh ./ci/backup-restore-test/backup.bash
      - sh ./ci/backup-restore-test/restore.bash
      - sh ./ci/backup-restore-test/dbswitch.bash
