version: 0.2

env:
  variables:
    WD: "app/api"
    IMAGE_REPO_NAME: "teet-api"
    IMAGE_TAG: "latest"
    ECS_TASK_NAME: "teet-api"
    AWS_DEFAULT_REGION: "eu-central-1"

  parameter-store:
    AWS_ACCOUNT_ID: "/teet/aws-account-id"

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - cd $WD && bash build.sh
      - docker tag mnt-teet/teet-api:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/teet-api:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/teet-api:latest
  post_build:
   commands:
     - cd ../..
     - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_TASK_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > api.imagedefinitions.json
artifacts:
   files: api.imagedefinitions.json
