version: 0.2

env:
  variables:
    WD: "app/api"

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - cd $WD && bash build.sh
      - docker tag mnt-teet/teet-api:latest 512288025010.dkr.ecr.eu-central-1.amazonaws.com/teet-registry/teet-api:latest
      - docker push 512288025010.dkr.ecr.eu-central-1.amazonaws.com/teet-registry/teet-api:latest
