version: 0.2

env:
  parameter-store:
    CYPRESS_SITE_PASSWORD: "/teet/api/basic-auth-password"

phases:
  install:
    runtime-version:
      nodejs: latest
    commands:
      - cd ci/browser-tests
      - npm install
  build:
    commands:
      - ./node_modules/cypress/bin/cypress run
      . ./slackreporter.clj
cache:
  paths:
    - '/root/.cache/**/*'
