version: 0.2

phases:
  install-clojure:
    commands:
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
      - bash linux-install-*.sh
  import:
    commands:
      - ci/datasource-import/import.bash


#  post_build:
#    commands:
#      - NOTIFY_ON_SUCCESS=1 bash $CODEBUILD_SRC_DIR/ci/scripts/slack.bash datasource-import

cache:
  paths:
    - '/root/.m2/**/*'
