@startuml TEET overview

title
	TEET system architecture overview
end title


!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/EndUserComputing/all.puml
!includeurl AWSPuml/Mobile/APIGateway.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Compute/Fargate.puml
!includeurl AWSPuml/Database/Aurora.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3.puml


actor "TEET Browser app (frontend)" as personAlias
(User prepared documents) as documentsAlias
Aurora(pgAlias, "PostgreSQL DB", "Geo data")


package "External systems" {
	(THK system) as thkAlias
	(Maa-amet maps) as mapsAlias
	(Delta) as deltaAlias
	(Maa-amet restrictions) as restrictionsAlias
	(Cadastral data) as cadastraldbAlias
}


mapsAlias <-- personAlias

note bottom of mapsAlias
	Front end requests map tiles from Maa-amet tile server
end note

Fargate(pgRestAlias, "PostgREST API", "HTTP access to PostgreSQL")
SimpleStorageServiceS3(storageAlias, "Stored docs", "Project-related uploaded files")
SimpleStorageServiceS3(integrationS3Alias, "THK integration data", "CSV files")
APIGateway(apigwAlias, "Frontend APIGW", "Web UI actions")

(TEET Geo data import tool) as importToolAlias
importToolAlias -up-> restrictionsAlias
importToolAlias -up-> cadastraldbAlias
importToolAlias --> pgRestAlias


package "Datomic" {
  (Datomic DB) as datomicAlias
  Lambda(queryIonAlias, "Query ion", "Read back information")
  Lambda(commandIonAlias, "Command ion", "Alter system state")
  Lambda(thkIntegrationIonAlias, "THK Integration ion", "Processes CSV files")
  Lambda(uploadProcessingIonAlias, "Upload processing ion", "uploaded files")

  note bottom of thkIntegrationIonAlias
	Datomic Cloud runs a set of compute nodes,
	each Datomic Ion has an associated Lambda which proxies requests to the compute nodes
  end note

  note right of datomicAlias
	Datomic DB data is backed by AWS DynamoDB, S3 & EBS services
  end note

}


personAlias --> apigwAlias
apigwAlias --> storageAlias
apigwAlias --> queryIonAlias
apigwAlias --> commandIonAlias
personAlias --> documentsAlias
documentsAlias --> storageAlias
integrationS3Alias <--> thkIntegrationIonAlias
thkAlias --> integrationS3Alias

thkIntegrationIonAlias <--> datomicAlias
queryIonAlias <--> datomicAlias
commandIonAlias <--> datomicAlias
uploadProcessingIonAlias <--> datomicAlias

Datomic -up-> pgRestAlias
uploadProcessingIonAlias <--> storageAlias

pgRestAlias --> pgAlias
personAlias --> pgRestAlias

note left of integrationS3Alias
	THK system periodically uploads CSV file to S3 integration bucket
end note

@enduml
