@startuml TEET overview

title
	TEET system architecture overview
end title
	

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/EndUserComputing/all.puml
!includeurl AWSPuml/Mobile/APIGateway.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Compute/Fargate.puml
!includeurl AWSPuml/Database/Aurora.puml
!includeurl AWSPuml/Storage/SimpleStorageServiceS3.puml


actor "TEET Browser app (frontend)" as personAlias
(User prepared documents) as documentsAlias
Aurora(pgAlias, "Aurora DB", "Geo data")


package "External systems" {
	(THK system) as thkAlias
	(Maa-amet maps) as mapsAlias
	(Delta) as deltaAlias
	(Maa-amet restrictions) as restrictionsAlias
	(Cadastral data) as cadastraldbAlias
}

(cadastral import automation TBD) as tbdImportProcess1
(restrictions import automation TBD) as tbdImportProcess2

mapsAlias --> personAlias
cadastraldbAlias --> tbdImportProcess1
tbdImportProcess1 --> pgAlias
restrictionsAlias --> tbdImportProcess2
tbdImportProcess2 --> pgAlias

Fargate(pgRestAlias, "PostgREST API", "HTTP access to Aurora data")
SimpleStorageServiceS3(storageAlias, "Stored docs", "Project-related uploaded files")
SimpleStorageServiceS3(integrationS3Alias, "THK integration data", "CSV files")
APIGateway(apigwAlias, "Frontend APIGW", "Web UI actions")

package "Datomic" {
  (Datomic DB) as datomicAlias
  Lambda(queryIonAlias, "Query ion", "Read back information")
  Lambda(commandIonAlias, "Command ion", "Alter system state")
  Lambda(thkIntegrationIonAlias, "THK Integration ion", "Processes CSV files")
  
  note bottom of thkIntegrationIonAlias
	Datomic ions run on a set of Datomic compute nodes,
	each is coupled with a Lambda
  end note

  note right of datomicAlias
	Datomic DB data is backed by AWS DynamoDB, S3 & EBS services
  end note

}


personAlias --> apigwAlias
apigwAlias --> storageAlias
apigwAlias --> queryIonAlias
apigwAlias --> commandIonAlias
personAlias --> documentsAlias
documentsAlias --> storageAlias
integrationS3Alias <--> thkIntegrationIonAlias
thkAlias --> integrationS3Alias

thkIntegrationIonAlias <--> datomicAlias
queryIonAlias <--> datomicAlias
commandIonAlias <--> datomicAlias

thkIntegrationIonAlias <--> pgRestAlias
queryIonAlias <--> pgRestAlias
commandIonAlias <--> pgRestAlias

pgRestAlias <-> pgAlias

note right of documentsAlias
	Associated to specific project tasks
end note

@enduml
