version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     java: openjdk8
  #   commands:
  #     - echo Download Clojure CLI tool
  #     - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
  #     - bash linux-install-1.10.1.466.sh
  build:
    commands:
      - ci/drift-detect/drift-detect.bash

  # post_build:
  #   commands:
  #     - NOTIFY_ON_SUCCESS=1 bash $CODEBUILD_SRC_DIR/ci/scripts/slack.bash Drift-detect $CODEBUILD_RESOLVED_SOURCE_VERSION
