version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y bash rlwrap curl
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - chmod +x linux-install-1.10.1.466.sh
      - sudo ./linux-install-1.10.1.466.sh
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo Directory `pwd` with contents `ls`
      - cd app/project-frontend/ && clj -m figwheel.main -O advanced -bo prod
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - mkdir dist
      - cp resources/public/index.html dist
      - cp target/public/cljs-out/prod-main.js dist/main.js
      - zip -jr target/build.zip dist
      - rm -rf dist
artifacts:
  files:
    - target/build.zip
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
