version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    BACKEND: "app/backend"
    AWS_DEFAULT_REGION: "eu-central-1"

  parameter-store:
    AWS_ACCOUNT_ID: "/teet/aws-account-id"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Download Clojure CLI tool
      - curl -o /tmp/install-clojure.sh https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash /tmp/install-clojure.sh
  build:
    commands:
      - cd $BACKEND
      - clojure -A:test
      - bash build.sh
  post_build:
    commands:
      - NOTIFY_ON_SUCCESS=0 && bash ../../ci/scripts/slack.bash Backend $COMMIT
cache:
  paths:
    - '/root/.m2/**/*'
