version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    BACKEND: "app/backend"
    AWS_ACCOUNT_ID: "512288025010"
    AWS_DEFAULT_REGION: "eu-central-1"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Download Clojure CLI tool
      - curl -o /tmp/install-clojure.sh https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash /tmp/install-clojure.sh
  build:
    commands:
      - cd $BACKEND
      - clojure -A:test
      - bash build.sh
cache:
  paths:
    - '/root/.m2/**/*'
