version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    BACKEND: "app/backend"
    AWS_ACCOUNT_ID: "512288025010"
    AWS_DEFAULT_REGION: "eu-central-1"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash linux-install-1.10.1.466.sh
  build:
    commands:
      - cd $BACKEND
      - bash build.sh
cache:
  paths:
    - '/root/.m2/**/*'
