version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "teet-db-migrate"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build . -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
