version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "download & install datomic cli"
      - wget https://datomic-releases-1fc2183a.s3.amazonaws.com/tools/datomic-cli/datomic-cli-0.10.82.zip
      - unzip datomic-cli*.zip
      - echo install --mode=755 datomic-cli/datomic* /usr/local/bin/

  build:
    commands:
      - ci/analytics-config-sync/sync.bash
