name: cypress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.510'
      - name: setup dev tools
        run: |
          export DEV_TOOLS_REPO_USER=${{ secrets.DEV_TOOLS_REPO_USER }}
          export DEV_TOOLS_REPO_PASS=${{ secrets.DEV_TOOLS_REPO_PASS }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ./ci/scripts/setup-dev-tools.bash
      - name: configure datomic local
        run: |
          mkdir ~/.datomic
          mkdir /tmp/datomic-storage
          export CYPRESS_SITE_PASSWORD=${{ secrets.CYPRESS_SITE_PASSWORD }}
          echo "{:storage-dir \"/tmp/datomic-storage\"}" > ~/.datomic/dev-local.edn
      - name: run backend build
        run: clojure -A:dev
        working-directory: app/backend/
      - name: run frontend build
        run: ./ci-build.sh
        working-directory: app/frontend/
      - name: run cypress
        run: npx cypress run --config-file /ci/browser-tests/cypress-localdev.json
        working-directory: ci/browser-tests/
